### ISSUE TITLE
some shortcuts don't work

### ISSUE THREAD

**Issue by negm98** [sduduzog/slim-launcher#30]
I posted this review on the store, then I found this repo. So, here is my issue again. sorry, for any inconvenience.
This app is exactly what I need. I have only one problem: not all homescreen shortcuts work on my phone. I can only launch the camera and the calendar. However, I can't launch either the clock or the phone's dialer. my system details:  OS: android 7.1.2 UI: Flyme 7.1.1.0G and the phone is rooted. I would highly appreciate fixing this issue.

**Comment by sduduzog** [comment]
HI, thanks for raising this. The phone dialler I'm sure I should get to and fix with less hassle. The clock shortcut has been an issue ever since this app was released last year. There's a number of devices that just choose to ignore my code for it, I know also some older samsung galaxy devices do this too.

 I haven't been available to work on the app for some time but I'll get on the dialler as soon as possible. It should be fixed and pushed to the play store before the weekend

**Comment by fain182** [comment]
I upgraded the app to the last version of yesterday but the dialer still don't work.

I am on a Moto X4 with android 9.

( Thanks for this great launcher! )

**Comment by sduduzog** [comment]
@fain182 I've made some minor code changes around that area but not yet pushed out. I'm still researching as to why this happens. I know now that Moto X4 has a modified version of the google dialler but I don't understand why it isn't working. I'm also trying to get my hands on one

**Comment by fain182** [comment]
thank you!
